USE [master]
GO

/****** Object:  Database [Widget]    Script Date: 12/10/2017 02:57:37 ******/
CREATE DATABASE [Widget]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Widget', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Widget.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Widget_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.SQLEXPRESS\MSSQL\DATA\Widget_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [Widget] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Widget].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Widget] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Widget] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Widget] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Widget] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Widget] SET ARITHABORT OFF 
GO

ALTER DATABASE [Widget] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Widget] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Widget] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Widget] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Widget] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Widget] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Widget] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Widget] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Widget] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Widget] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Widget] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Widget] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Widget] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Widget] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Widget] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Widget] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Widget] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Widget] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Widget] SET  MULTI_USER 
GO

ALTER DATABASE [Widget] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Widget] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Widget] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Widget] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Widget] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Widget] SET QUERY_STORE = OFF
GO

USE [Widget]
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [Widget] SET  READ_WRITE 
GO


