INSERT INTO [dbo].[User] VALUES (1, 'Steve Rogers', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Captain-America-icon.png')
INSERT INTO [dbo].[User] VALUES (2, 'Tony Stark "Iron Man"', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Iron-Man-icon.png')
INSERT INTO [dbo].[User] VALUES (3, 'Bruce Banner "Hulk"', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Hulk-icon.png')
INSERT INTO [dbo].[User] VALUES (4, 'James Rhodes', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-War-Machine-icon.png')
INSERT INTO [dbo].[User] VALUES (5, 'Natasha Romanoff', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Black-Widow-icon.png')
INSERT INTO [dbo].[User] VALUES (6, 'Clinton Francis Barton', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Hawkeye-icon.png')
INSERT INTO [dbo].[User] VALUES (7, 'Thor', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Thor-icon.png')
INSERT INTO [dbo].[User] VALUES (8, 'Clark Gregg', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Agent-Coulson-icon.png')
INSERT INTO [dbo].[User] VALUES (9, 'Nick Fury', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Nick-Fury-icon.png')
INSERT INTO [dbo].[User] VALUES (10, 'Hank Pym', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Giant-Man-icon.png')
INSERT INTO [dbo].[User] VALUES (11, 'James Howlett "Logan"', 'http://iconbug.com/data/4a/128/21e6f393eaf39654925d1cb06557cf1b.png')
INSERT INTO [dbo].[User] VALUES (12, 'Erik Magnus Lehnsherr', 'https://cdn1.iconfinder.com/data/icons/UltraBuuf/512/Magneto.png')

