INSERT INTO [dbo].[User] VALUES ('Steve Rogers', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Captain-America-icon.png')
INSERT INTO [dbo].[User] VALUES ('Tony Stark "Iron Man"', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Iron-Man-icon.png')
INSERT INTO [dbo].[User] VALUES ('Bruce Banner "Hulk"', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Hulk-icon.png')
INSERT INTO [dbo].[User] VALUES ('James Rhodes', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-War-Machine-icon.png')
INSERT INTO [dbo].[User] VALUES ('Natasha Romanoff', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Black-Widow-icon.png')
INSERT INTO [dbo].[User] VALUES ('Clinton Francis Barton', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Hawkeye-icon.png')
INSERT INTO [dbo].[User] VALUES ('Thor', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Thor-icon.png')
INSERT INTO [dbo].[User] VALUES ('Clark Gregg', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Agent-Coulson-icon.png')
INSERT INTO [dbo].[User] VALUES ('Nick Fury', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Nick-Fury-icon.png')
INSERT INTO [dbo].[User] VALUES ('Hank Pym', 'http://icons.iconarchive.com/icons/hopstarter/superhero-avatar/72/Avengers-Giant-Man-icon.png')
INSERT INTO [dbo].[User] VALUES ('James Howlett "Logan"', 'http://iconbug.com/data/4a/128/21e6f393eaf39654925d1cb06557cf1b.png')
INSERT INTO [dbo].[User] VALUES ('Erik Magnus Lehnsherr', 'https://cdn1.iconfinder.com/data/icons/UltraBuuf/512/Magneto.png')